_includes/head.html
_sass/_docs.scss
docs.html

This PR adds an API section to the doc outlining all the methods and parameters available. It also switches the using the version of HanziWriter server from the jsdelivr CDN.

Full api docs

---

src/HanziWriter.js
src/Quiz.js
src/renderers/StrokeRenderer.js
src/svg.js

This PR fixes 2 regressions 
- A regression from #35 which causes multiple calls to any animation methods like `animate()` or `hide()` or `show()` before the previous command completed to stack one after another rather than immediately ending the previous animation and replacing it.
- A regression from #24 which causes cancelled opacity animations to end up in a partially opaque state.

fixing partial opacity and cancelation regressions

---

src/HanziWriter.js
src/defaultCharDataLoader.js

The user-defined function is now given a reject callback to trigger error
conditions while loading new character data. Please note that the
running code (not the user-defined function) is also given a chance to
reject the promise (and thus trigger the calling of the error callback)
when it receives a second loading request before the current one is
finished.
This should fix the issues with the error being reported only on next call 
if user-defined function doesn't handle errors itself correctly.
Please note that it doesn't provide a radical change of the API of the user defined function as I suggested in an open issue #41 ... and thus should remain mostly compatible with any custom made user function.

fix: better error loading of char data

---

src/Animator.js
src/HanziWriter.js

This fixes a bug where if you load a new character while a character animation is looping, it will either throw an error or continue looping when the next character loads. Pointed out by @vaab in https://github.com/chanind/hanzi-writer/issues/50.

fixing bug loading a new character while looping

---

babel-jest-processor.js
demo/test.js
package.json
src/HanziWriter.js
src/LoadingManager.js
src/__tests__/HanziWriter-test.js
src/__tests__/LoadingManager-test.js
yarn.lock

This PR adds some tests and minor tweaks to the loading manager. Specifically, it will throw an error if loading fails and no `onLoadCharDataError` callback is provided.

Loading manager tests

---

package.json
src/HanziWriter.js
src/__tests__/HanziWriter-test.js
src/__tests__/defaultCharDataLoader-test.js
src/defaultCharDataLoader.js
yarn.lock

This PR removes the auto-retry in `_withData` as discussed with @vaab in #42. It also fixes a bug where `onError` is called twice in case of network failure using the default data loader.

No auto retry load

---

src/__tests__/Quiz-test.js
src/quizActions.js

This PR fixes a bug where the whole character becomes highlighted when the users restarts a quiz after first finishing a quiz successfully. The stroke highlight opacities were not being reset properly before.

fixing character highlight bug on second quiz

---

src/Quiz.js
src/__tests__/Quiz-test.js
src/__tests__/svg-test.js
src/geometry.js
src/svg.js

This PR rounds the `points` and `pathString` returned in `drawnPath` to 1 decimal place.
fixes #66

Rounded path strings

---

src/RenderState.js
src/__tests__/Quiz-test.js
src/characterActions.js
src/quizActions.js

This is a regression on #43. Also adding tests on this case.

fixing a bug where strokes can be partially opaque when quizzing quickly

---

src/HanziWriter.js
src/Quiz.js
src/__tests__/HanziWriter-test.js
src/__tests__/Quiz-test.js
src/characterActions.js
src/quizActions.js

This PR is a completed version of https://github.com/chanind/hanzi-writer/pull/54 that works with the new animation / rendering architecture. This PR adds a new option `highlightCompleteColor` which can be set to control the color that is flashed when a quiz is completed successfully.
closes #49

Adding a separate option for highlightCompleteColor

---

src/HanziWriter.js
src/__tests__/HanziWriter-test.js

Settings `duration: 0` when calling a show/hide method, ex `showCharacter({ duration: 0 })` should cause the method to complete immediately. However, this was broken because 0 is also considered falsy. This PR fixes this by explicitly checking `typeof options.duration === 'number'` instead.

fixing a bug where duration: 0 is ignored for show/hide methods

---

src/HanziWriter.js
src/__tests__/HanziWriter-test.js

As discussed in #55, this PR simplifies the behavior of `new HanziWriter()` while maintaining backwards compatibility. This PR thus allows setup via the following methods:
1. `writer = new HanziWriter('target', '人', options)` original behavior. This will now `console.warn` that this is deprecated.
2. `writer = HanziWriter.create('target', '人', options)` Helper which mimics old constructor behavior
3. `writer = new HanziWriter('target', options); writer.setCharacter('人');`
4. `writer = new HanziWriter(); writer.init('target', options); writer.setCharacter('人');`
I'm leaning towards removing option `[4]` above, since it's a bit awkward with needing to call `writer.init('target', options)` after `new HanziWriter()` but before `setCharacter()`, which seems a bit verbose. But it's maybe also …

Simplifying constructor, but keeping backwards compatibility

---

src/__tests__/strokeMatches-test.js
src/strokeMatches.js

fixes #90 
This PR changes matching logic so that if the user draws a stroke which matches an incorrect stroke better than the desired stroke it will not automatically fail. Instead, this will take into account the stroke matching leniency setting and make it less likely for the stroke to match.
More details in #90

More leniency matching similar strokes near each other

---

src/HanziWriter.js
src/Mutation.js
src/__tests__/HanziWriter-test.js
src/characterActions.js

closes #91 
This PR adds a `writer.animateStroke(strokeNum, options = {})` method which can be used to animate a single stroke at a time. It works similar to `writer.animateCharacter(options = {})`, with the same options and similarly returning a promise which resolves when the stroke is finished animating.

adding a writer.animateStroke() method

---

README.md
src/HanziWriter.js
src/__tests__/HanziWriter-test.js

This PR fixes a bug where calling `setCharacter()` would reset the character opacity and outline opacity back to their original value when the writer instance was created.
fixes #101

Fix reset outline on set character

---

src/strokeMatches.js

normalizeCurve(curve) in geometry.js has only one parameter

fix(strokeMatches) remove unused parameter

---

.gitignore
package.json
src/renderers/StrokeRenderer.js
src/renderers/__tests__/StrokeRenderer-test.js
src/strokeMatches.js
src/svg.js

This PR adds `window.location.href` to the urls in clip masks to fix a bug in mobile Sarafi with relative urls. More details here: https://talk.observablehq.com/t/hanzi-writer-renders-incorrectly-inside-an-observable-notebook-on-a-mobile-browser/1898/2
Thanks @mbostock for figuring this out! (and also for d3 :)
fixes #104

Fixing safari stroke mask rendering bug

---

src/LoadingManager.js
src/__tests__/LoadingManager-test.js

This PR fixes a bug where calling `setCharacter()` multiple times while a character is loading, then calling `setCharacter()` again causes rendering to break.
Thanks @josephjohnston for finding this bug!
fixes #129

fix: calling setCharacter multiple times quickly breaks rendering

---

src/renderers/canvas/HanziWriterRenderer.js

解决ios系统无法显示汉字动画的问题

---

src/HanziWriter.js
src/__tests__/HanziWriter-test.js
src/characterActions.js
src/quizActions.js

This PR adds a `writer.highlightStroke(strokeNum, options = {})` method which can be used to manually highlight a stroke identically to what occurs in character quizzes. Thanks to @killia15 for the suggestion!
fixes #145

feat: adding writer.highlightStroke() method

---

src/HanziWriter.js
src/Mutation.js
src/RenderState.js
src/__tests__/HanziWriter-test.js
src/__tests__/Mutation-test.js
src/__tests__/RenderState-test.js
src/characterActions.js

This PR adds a `writer.pauseAnimation()` method and `writer.resumeAnimation()` method. These will pause and resume any currently running animation, respectively.
Thanks @silent717120 for the feature request!
closes #155

feat: pauseAnimation and resumeAnimation

---

src/__tests__/HanziWriter-test.js
src/renderers/canvas/RenderTarget.js
src/renderers/canvas/__tests__/RenderTarget-test.js
src/renderers/svg/RenderTarget.js

This PR explicitly throws an error `HanziWriter target element not found: <missing id>` when the library is initialized with a non-existent div as the render target. Currently the library will error trying to call `nodeName` of `undefined`, which is a very confusing error.

fix: better error message if render target not found

---

demo/test.js
src/renderers/svg/CharacterRenderer.js
src/renderers/svg/__tests__/CharacterRenderer-test.js
src/utils.js

This PR fixes an SVG animation bug in IE/Edge where the first stroke of the character just animates a tiny bit, but then the rest of the character animates correctly.
After further investigation, it seems like this bug only happens if the `<g>` tag of the SVG is set to `display:none` when the SVG is first rendered in the dom. If the SVG is later set to `display:none`, there's no issue. HanziWriter sets `display:none` as a performance optimization when a character layer has 0 opacity to keep the browser from trying to render the SVG at all, so this PR just removes that optimization for Microsoft browsers (IE and Edge).
Thanks to @bastianspirek for finding this bug!
fixes #164

fix: IE/Edge SVG animation bug

---

src/HanziWriter.js
src/renderers/svg/HanziWriterRenderer.js
src/renderers/svg/__tests__/StrokeRenderer-test.js

`UserStrokeRenderer.prototype.mount(target)` and `(svg|canvas)/HanziWriterRenderer.prototype.mount(target)` do not have a second param on their function definitions, while some calls to these functions are invoking `.mount(target, props)`. It looks like the second parameter given to these functions are instead now used in a subsequent call to `xxxx.render(props)`

update(HanziWriterRenderer) remove extra param on .mount() call

---

src/HanziWriter.js

Didn't seem used anywhere in the project. The conditions it's used in will always be false.

update(HanziWriter) remove undef variable "this.isLoadingCharData"

---

src/Quiz.js
src/__tests__/Quiz-test.js

The docs mention in multiple places that setting "showHintAfterMisses" to false will disable hint stroke highlighting. This isn't the case and instead highlights after every mistake. This commit fixes the issue.

fix(Quiz) Don't highlight stroke when setting "showHintAfterMisses" to false

---

jest-jsdom-env.js
package.json
src/renderers/svg/__tests__/StrokeRenderer-test.ts
src/renderers/svg/__tests__/svgUtils-test.ts
src/renderers/svg/svgUtils.ts

This PR wraps the url passed to `clip-path` in double quotes ("), and escapes any quotations inside the URL. This should fix the issue where URLs that have parentheses in them cause hanzi-writer to break.
fixes #215

escaping the URL passed to clip-path to handle parentheses

---

babel.config.js

The current compile target for babel is the current node release, which is too modern. This PR changes the compile targets to target some older browsers and older node versions.
Hopefully this will fix #219 and fix #220

fix: support older node and browser versions

---

src/HanziWriter.ts
src/__tests__/HanziWriter-test.ts

This PR adds a method `writer.getCharacterData()`, which returns a promise containing the parsed character data after it's loaded. This is to provide a more usable method to get info about the currently loaded character without needing to do anything hacky around reading internals like `writer._character`. This promise will always return the character data or error if it's not possible.
This character data contains the currently loaded character symbol (ex `我`), and an array of `strokes` containing the stroke data needed to render the character. This is probably most useful to determine how many strokes there are in the character.
related to #222

adding a getCharacterData() method for easier access to loaded character data

---

package.json
src/HanziWriter.ts
src/Quiz.ts
src/RenderState.ts
src/__tests__/HanziWriter-test.ts
src/__tests__/Quiz-test.ts
src/renderers/RenderTargetBase.ts
src/typings/types.ts
yarn.lock

This PR adds an `updateDimensions({ width, height, padding })` method, which will update the size of an existing HanziWriter instance without needing to recreate the instance and without needing to reset the render state.
closes #244

feat: adding writer.updateDimensions method

---

src/Quiz.ts
src/__tests__/Quiz-test.ts
src/__tests__/strokeMatches-test.ts
src/defaultOptions.ts
src/strokeMatches.ts
src/typings/types.ts

The use case for this is to allow applications to notify a user when they make a backwards stroke (one which is correct except for the direction in which in which it's made) on a quiz. In such a case, the application will likely want to show some messaging to the user indicating the stroke was made in the wrong direction. The application may want to treat backwards strokes as correct or incorrect.
This change includes two API changes to fulfill the above use case:
- The addition of a `checkBackwardsStrokes` ternary quiz option (defaulted off)
- The `onCorrectStroke` and `onMistake` quiz handlers receive an `isBackwards` boolean property on the stroke data.
`checkBackwardsStrokes` is ternary to allow avoiding the perf hit of checking backwards strokes if the application does not care about …

feat: allow checking backwards strokes

---

src/HanziWriter.ts
src/Quiz.ts
src/__tests__/HanziWriter-test.ts
src/__tests__/Quiz-test.ts
src/defaultOptions.ts
src/quizActions.ts
src/typings/types.ts
src/utils.ts
yarn.lock

This PR adds a `quizStartStrokeNum` option which can be used to start the quizzing at a stroke other than stroke 0, to support quizzing just the final stroke if desired.
This PR also adds support for passing negative indices into `quizStartStrokeNum`, `animateStroke` and `highlightStroke` to allow selecting the final stroke without needing to calculate how many strokes are present in the character.
Thanks to @rdrg109 for the idea!
closes #280

feat: add quizStartStrokeNum option to allow quizzing final stroke

---

demo/test.js
src/Mutation.ts
src/Quiz.ts
src/__tests__/Quiz-test.ts
src/characterActions.ts
src/quizActions.ts

This PR uses the `highCompleteColor` when highlighting the character after finishing a quiz rather than ignoring the param and just using `highlightColor`. Thank you @GnitLores for finding this bug!
related to #292.

fix: respect highlightCompleteColor when finishing quiz

---

src/__tests__/HanziWriter-test.ts
src/characterActions.ts

Currently, if a stroke highlight animation gets interrupted it just leaves the stroke highlight in whatever state it's in mid-animation. This PR fixes this to force the highlight to disappear when it gets interrupted rather than hanging around looking strange. Thank you to @GnitLores for finding this!
fixes #292

fix: hide stroke highlight if it gets canceled

---

demo/test.js
src/Quiz.ts
src/__tests__/Quiz-test.ts
src/defaultOptions.ts
src/typings/types.ts

This PR adds a `markStrokeCorrectAfterMisses` option to `new HanziWriter()` and `HanziWriter.quiz()` which allows setting a number of mistakes after which the users's stroke will be marked correct no matter what. Thank you to @ ganqqwerty for the feature suggestion!
closes #289

feat: adding markStrokeCorrectAfterMisses option to quizzes

---

src/Quiz.ts
src/defaultOptions.ts
src/strokeMatches.ts
src/typings/types.ts

This pull request introduces an averageDistanceThreshold option to the strokeMatches function, allowing users to configure the leniency of stroke matching based on distance.
This change provides more flexibility for users who want to adjust the leniency of stroke matching, especially in scenarios where the direction of the stroke is more important than its exact position.

Add averageDistanceThreshold Option for Stroke Matching Leniency

---

src/HanziWriter.ts
src/Quiz.ts
src/__tests__/HanziWriter-test.ts
src/__tests__/Quiz-test.ts

This feature adds a function skipStrokeQuiz, that can be used while in a quiz to skip a stroke. This is useful for e.g. 圖, since hanzi writer has a hard time recognizing the short strike under the upper inner box of

feat: Added skipStrokeQuiz

---

src/Quiz.ts
src/__tests__/Quiz-test.ts
src/quizActions.ts

When drawing a Hanzi character in quiz mode on mobile devices, certain strokes were being interrupted or stopped halfway through when wrote quickly. This was caused by the touchmove event ceasing to fire. The root issue was that a node within the SVG element was being removed during the stroke drawing process, disrupting the touch event stream.
I found this issue which relates a similar problem : https://stackoverflow.com/questions/29384973/touchmove-event-stops-triggering-after-any-element-is-removed-from-dom
Instead of removing strokes immediately after they are drawn, I modified the logic to preserve the strokes by keeping their corresponding IDs. These strokes are now removed only at the end of the quiz session (on cancel or startQuiz). This prevents disruption of the touchmove event …

Fix: Ensure consistent stroke drawing in quiz mode on mobile

---

src/utils.ts

On Firefox 132.0.1 (aarch64) on macOS, I get this error:
`TypeError: 'requestAnimationFrame' called on an object that does not implement interface Window.` (from `Mutation.ts` line 134)
And the same error for `cancelAnimationFrame`
I don't get that error on Safari or Chrome on the same machine.
Binding them to the global object fixes that error for me.

Fix: TypeError: 'requestAnimationFrame' called on an object that does not implement interface Window.
